/* auto-generated by NAPI-RS */
/* eslint-disable */

/** Aggregate leaf proofs into a private-batch proof (layer 1). */
export declare function aggregatePrivateBatch(leafProofs: Array<Uint8Array>): Promise<Uint8Array>

/** Aggregate private-batch proofs into a public-batch proof (layer 2). */
export declare function aggregatePublicBatch(privateBatchProofs: Array<Uint8Array>, aggregatorAddress: string): Promise<Uint8Array>

export declare function decodeZkLeaf(bytes: Uint8Array): ZkLeaf

export declare function dequantize(quantized: number): string

export declare function encodeVerifyPrivateBatch(proof: Uint8Array): Uint8Array

export declare function encodeVerifyPublicBatch(proof: Uint8Array): Uint8Array

export interface Exit {
  account: string
  amount: number
}

export declare function extrinsicHash(xt: Uint8Array): string

/** Size the rayon pool used for proving. Call once before proving. */
export declare function initThreadPool(threads: number): void

export interface LeafInput {
  secret: string
  transferCount: number
  wormholeAddress: string
  inputAmount: number
  blockHash: string
  blockNumber: number
  parentHash: string
  stateRoot: string
  extrinsicsRoot: string
  digest: string
  zkTreeRoot: string
  sortedSiblings: Array<Array<string>>
  positions: Array<number>
  exitAccount1: string
  outputAmount1: number
  exitAccount2: string
  outputAmount2: number
  volumeFeeBps: number
  assetId: number
}

export interface LeafProof {
  proof: Uint8Array
  nullifier: Uint8Array
}

export interface LeafPublicInputs {
  assetId: number
  outputAmount1: number
  outputAmount2: number
  volumeFeeBps: number
  nullifier: string
  exitAccount1: string
  exitAccount2: string
  blockHash: string
  blockNumber: number
  inputAmount: number
}

export interface MerklePath {
  sortedSiblings: Array<Array<string>>
  positions: Array<number>
  root: string
}

export declare function merklePositions(unsorted: Array<Array<string>>, leafHash: Uint8Array): MerklePath

export declare function nullifier(secret: Uint8Array, transferCount: number): Uint8Array

export declare function numLeafProofs(): number

export declare function numPrivateBatchProofs(): number

export declare function outputAfterFee(input: number, feeBps: number): number

export declare function parseLeafProof(proof: Uint8Array): LeafPublicInputs

export declare function parsePrivateBatchProof(proof: Uint8Array): PrivateBatchPublicInputs

export declare function parsePublicBatchProof(proof: Uint8Array): PublicBatchPublicInputs

export interface PrivateBatchPublicInputs {
  numExitSlots: number
  assetId: number
  volumeFeeBps: number
  blockHash: string
  blockNumber: number
  exits: Array<Exit>
  nullifiers: Array<string>
}

/** Prove one deposit (layer 0). */
export declare function proveLeaf(i: LeafInput): Promise<LeafProof>

export interface PublicBatchPublicInputs {
  aggregatorAddress: string
  assetId: number
  volumeFeeBps: number
  blockHash: string
  blockNumber: number
  totalExitSlots: number
  segments: Array<Segment>
}

export declare function quantize(plancks: string): number

export interface Segment {
  exits: Array<Exit>
  nullifiers: Array<string>
}

export declare function threadCount(): number

export declare function usedNullifierStorageKey(nullifier: Uint8Array): string

export declare function verifyLeafProof(proof: Uint8Array): LeafPublicInputs

export declare function verifyPrivateBatchProof(proof: Uint8Array): PrivateBatchPublicInputs

export declare function verifyPublicBatchProof(proof: Uint8Array): PublicBatchPublicInputs

export interface WormholeAccount {
  accountId: string
  address: string
  secret?: string
}

export declare function wormholeAddress(secret: Uint8Array): WormholeAccount

export declare function wormholeFromMnemonic(mnemonic: string, index: number, passphrase?: string | undefined | null): WormholeAccount

export interface ZkLeaf {
  to: string
  transferCount: string
  assetId: number
  amount: string
}
